In [1]:
import tensorflow as tf

# Creating Tensors

In [2]:
string=tf.Variable("String",tf.string)
num=tf.Variable(123,tf.int16)
flt=tf.Variable(1.23,tf.float64)

In [3]:
string

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'String'>

In [4]:
num

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=123>

In [5]:
flt

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=1.23>

# Rank/Degree of Tensors

In [12]:
rank1_tensor=tf.Variable(["a","b"],tf.string)
rank2_tensor=tf.Variable([["a","b"],["c","d"]],tf.string)

In [13]:
rank1_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=string, numpy=array([b'a', b'b'], dtype=object)>

In [14]:
rank2_tensor

<tf.Variable 'Variable:0' shape=(2, 2) dtype=string, numpy=
array([[b'a', b'b'],
       [b'c', b'd']], dtype=object)>

In [17]:
tf.rank(num)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [15]:
tf.rank(rank1_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [16]:
tf.rank(rank2_tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

# Shape of Tensor

In [19]:
rank1_tensor.shape

TensorShape([2])

In [20]:
rank2_tensor.shape

TensorShape([2, 2])

In [21]:
num.shape

TensorShape([])

# Changing Shape

In [29]:
tensor1=tf.ones([1,2,3])
tensor1

<tf.Tensor: shape=(1, 2, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [30]:
tensor2=tf.reshape(tensor1,[2,3,1])
tensor2

<tf.Tensor: shape=(2, 3, 1), dtype=float32, numpy=
array([[[1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.]]], dtype=float32)>

In [31]:
tensor3=tf.reshape(tensor2,[3,-1])
tensor3

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>